# -*- coding: utf-8 -*-
"""sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xa-EA8w6T3uoj2nSW35s84pfWkOzA8JA
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("/content/Dataset for Data Analytics new(2).xlsx")
df.head()

df.shape

df.columns

df.info()

df.isnull().sum()
df.describe()

# For categorical column
df["Product"].value_counts()

# For numeric columns
df["Quantity"].mean()
df["Quantity"].median()

df["TotalPrice"].mean()
df["TotalPrice"].median()

#Correlation
df.corr(numeric_only=True)

#Heatmap (visual pattern)
plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

#Histogram (distribution)
plt.figure()
df["Product"].hist()
plt.title("Distribution")
plt.show()

#Identify Outliers
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df["Quantity"] < Q1 - 1.5*IQR) |
              (df["Quantity"] > Q3 + 1.5*IQR)]

outliers