# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nbNHn0Ok1FKAjOlROytoP3xYVbSQj8w
"""

# Import required libraries
import pandas as pd
import sqlite3

# Load Excel file
df = pd.read_excel('/content/Dataset for Data Analytics new(2).xlsx')

# Display first 5 rows
df.head()

# Create connection to SQLite database
conn = sqlite3.connect('project3.db')

# Store dataframe as SQL table
df.to_sql('orders', conn, if_exists='replace', index=False)

# Select all records
query = "SELECT * FROM orders LIMIT 10"

result = pd.read_sql(query, conn)
print(result)

# Filter delivered orders
query = """
SELECT OrderID, Product, OrderStatus
FROM orders
WHERE OrderStatus = 'Delivered'
LIMIT 10
"""

result = pd.read_sql(query, conn)
print(result)

# Sort by highest total price
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10
"""

result = pd.read_sql(query, conn)
print(result)

# Count orders by payment method
query = """
SELECT PaymentMethod, COUNT(*) as Total_Orders
FROM orders
GROUP BY PaymentMethod
"""

result = pd.read_sql(query, conn)
print(result)

# Average total price by product
query = """
SELECT Product, AVG(TotalPrice) as Average_Price
FROM orders
GROUP BY Product
"""

result = pd.read_sql(query, conn)
print(result)

# Total sales by product
query = """
SELECT Product, SUM(TotalPrice) as Total_Sales
FROM orders
GROUP BY Product
ORDER BY Total_Sales DESC
"""

result = pd.read_sql(query, conn)
print(result)

# Find cancelled orders
query = """
SELECT Product, COUNT(*) as Cancelled_Count
FROM orders
WHERE OrderStatus = 'Cancelled'
GROUP BY Product
ORDER BY Cancelled_Count DESC
"""

result = pd.read_sql(query, conn)
print(result)

